[package]
name = "cezar-16"
version = "0.1.0"
edition = "2021"
default-run = "cezar-16"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
